repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^misc/k8s/.*$
    -   id: end-of-file-fixer
        exclude: ^(.*_pb2.*.py)$
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.16
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-gfm
    - mdformat-black
    - mdformat-config
    - mdformat-beautysh
    - mdformat-toc
-   repo: https://github.com/PyCQA/pylint
    rev: v3.0.0a6
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
            [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--ignore-patterns=.*_pb2.*.py"
            ]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        exclude: ^(.*_pb2.*.py)$
-   repo: https://github.com/pre-commit/mirrors-mypy
    # Mypy is a static type checker for Python
    rev: v1.1.1
    hooks:
    -   id: mypy
-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    -   id: dockerfilelint
